##################################################
#                                                #
#              XP multiplyer value               #
#                                                #
##################################################
dxp: 2

##################################################
#                                                #
#  Playercount needed to activate xp multiplyer  #
#                                                #
##################################################
dpc: 5